rails/alpha-blog/config/routes.rb
Rails.application.routes.draw do

  
  get 'pages/home', to: 'pages#home'
  get 'pages/about', to: 'pages#about'

end

rails/alpha-blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails/alpha-blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def about
    end
end

rails/alpha-blog/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/alpha-blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

rails/alpha-blog/app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Ruby Facts</title>
<meta charset="UTF-8">
<style>
header, footer {
    padding: 1em;
    color: white;
    clear: left;
    text-align: center;
}

h1 {
    color: #b30000;
    font-family: courier;
    font-size: 300%;
}
p  {
    color: #b30000;
    font-family: verdana;
    font-size: 160%;
}

body {
	  background-color:black;
}

ul {
	list-style-type:circle;
	color: #b30000;
	text-align: left;
}

ul.menu {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333333;
}

li.menu {
    float: left;
}

li.menu a {
    display: block;
    color: white;
    text-align: center;
    padding: 16px;
    text-decoration: none;
}

li.menu a:hover {
    background-color: #111111;
}

i{
	color: white;
}

article {
	background-color:#333333;
	text-align: center;
    width:80%;
	margin-left: auto;
    margin-right: auto;	
}

div.back {

	margin-left: auto;
    margin-right: auto;	
	width:960px;
	height:640px;
	background-image: url('http://test.dantas.me/img/jewelry-625724_960_720.jpg');
	text-align: center;	
	background-repeat: no-repeat;
}

</style>
</head>
<body>
    
<div class="back">
<ul class="menu">
  <li class="menu"><%= link_to 'Home', pages_home_path %></li>
  <li class="menu"><%= link_to 'About', pages_about_path %></li>
</ul>  

<header>
<h1>About author</h1>
</header>

<article>
<p>Fernando Dantas</p>
<ul>
  <li>Learning Ruby on Rails</li>
  <li>Moving to <b><i>Canada</i></b> next year!</li>
  <li>Looking for a remote job!!! </li>
</ul>
</article>
</div>

<footer>Copyright &#169; Fernando Dantas</footer>
</body>
</html>

rails/alpha-blog/app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Ruby Facts</title>
<meta charset="UTF-8">
<style>
header, footer {
    padding: 1em;
    color: white;
    clear: left;
    text-align: center;
}

h1 {
    color: #b30000;
    font-family: courier;
    font-size: 300%;
}
p  {
    color: #b30000;
    font-family: verdana;
    font-size: 160%;
}

body {
	  background-color:black;
}

ul {
	list-style-type:circle;
	color: #b30000;
	text-align: left;
}

ul.menu {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333333;
}

li.menu {
    float: left;
}

li.menu a {
    display: block;
    color: white;
    text-align: center;
    padding: 16px;
    text-decoration: none;
}

li.menu a:hover {
    background-color: #111111;
}

i{
	color: white;
}

article {
	background-color:#333333;
	text-align: center;
    width:80%;
	margin-left: auto;
    margin-right: auto;	
}

div.back {

	margin-left: auto;
    margin-right: auto;	
	width:960px;
	height:640px;
	background-image: url('http://test.dantas.me/img/jewelry-625724_960_720.jpg');
	text-align: center;	
	background-repeat: no-repeat;
}

</style>
</head>
<body>
    
<div class="back">
<ul class="menu">
  <li class="menu"><%= link_to 'Home', pages_home_path %></li>
  <li class="menu"><%= link_to 'About', pages_about_path %></li>
</ul>  
<header>
<h1>Starting with Ruby on Rails</h1>
</header>

<article>
<p>Rails Quick Facts</p>
<ul>
  <li>Follows MVC - Model, View, Controller</li>
  <li>The <b><i>rails new MySite</i></b> command create a new Rails app named MySite. It generated a number of files and folders that you will use to build the app. </li>
  <li>The <b><i>rails server</i></b> command started the Rails development server so that you can preview the app in the browser by visiting http://localhost:8000. This development server is called WEBrick. Another way to start is <i>rails s -p $PORT -b $IP</i></li>
</ul>
</article>
</div>

<footer>Copyright &#169; Fernando Dantas</footer>
</body>
</html>